[package]
name = "n2yo"
version = "0.1.0"
authors = ["Brian Daniels <brianddaniels@gmail.com>"]
edition = "2018"

[dependencies]
reqwest = "0.9.18"
serde = "1.0"
serde_json = "1.0"

[dev-dependencies]
mockito = "0.17.1"
